export default {
    name: 'portfolio',
    title: 'نمونه‌کارها',
    type: 'document',
    fields: [
        { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title_en' } },
        { name: 'title_en', title: 'Title (EN)', type: 'string' },
        { name: 'title_fa', title: 'Title (FA)', type: 'string' },
        { name: 'category_en', title: 'Category (EN)', type: 'string' },
        { name: 'category_fa', title: 'Category (FA)', type: 'string' },
        { name: 'description_en', title: 'Description (EN)', type: 'text' },
        { name: 'description_fa', title: 'Description (FA)', type: 'text' },
        { name: 'cover_image', title: 'Cover Image', type: 'image', options: { hotspot: true } },
        { name: 'gallery', title: 'Gallery', type: 'array', of: [{ type: 'image', options: { hotspot: true } }] },
        { name: 'featured', title: 'Featured', type: 'boolean' },
        { name: 'status', title: 'Status', type: 'string', options: { list: ['published', 'draft'] }, initialValue: 'draft' },
        { name: 'tags', title: 'Tags', type: 'array', of: [{ type: 'string' }] },
        { name: 'date_created', title: 'Date Created', type: 'datetime', initialValue: () => new Date().toISOString() },
    ],
}